<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_AxisControl" Id="{5be60846-58a1-496b-ab38-aa8e689397e9}" SpecialFunc="None">
    <Declaration><![CDATA[(*
Standard control for FB_AxisRef
*)

FUNCTION_BLOCK ABSTRACT FB_AxisControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	axisRef : Tc2_MC2.AXIS_REF;	
	fbMCPower : Tc2_MC2.MC_Power;
	fbMCHome : Tc2_MC2.MC_Home;
	fbMCStop : Tc2_MC2.MC_Stop;
	//Discrete motion
	fbMCMoveAbsolute : Tc2_MC2.MC_MoveAbsolute;
	fbMCMoveRelative : Tc2_MC2.MC_MoveRelative;
	fbMCMoveAdditive : Tc2_MC2.MC_MoveAdditive;
	fbMCMoveSuperImposed : Tc2_MC2.MC_MoveSuperImposed;
	fbMCHalt :  Tc2_MC2.MC_Halt;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_ContinuousMotion" Id="{8a5faf80-3892-4315-a42d-21702a6a09ad}">
      <Declaration><![CDATA[METHOD PUBLIC M_ContinuousMotion : HRESULT
VAR_INPUT
END_VAR
VAR_INST
	
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Disabled" Id="{9221797a-1e9a-455a-9548-f36d023ac1e2}">
      <Declaration><![CDATA[METHOD PROTECTED M_Disabled : HRESULT
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Discrete" Id="{fc76ca2c-e261-4cc9-a986-b84fa3dfd3f3}">
      <Declaration><![CDATA[METHOD M_Discrete : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Homing" Id="{08f2a54e-db5b-4d5e-8fff-13b43d554d14}">
      <Declaration><![CDATA[METHOD M_Homing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_StandStill" Id="{a040644f-fd6c-4fdb-b755-962a3d970bee}">
      <Declaration><![CDATA[METHOD M_StandStill : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stopping" Id="{107eb20a-062e-483b-84ec-b6b000b7e4b3}">
      <Declaration><![CDATA[METHOD M_Stopping : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_SynchrinizedMotion" Id="{89ba9017-30dc-4f71-a661-c8d7ce704253}">
      <Declaration><![CDATA[METHOD PUBLIC M_SynchrinizedMotion : HRESULT
VAR_INPUT
END_VAR
VAR_INST
	
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_AxisControl">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_ContinuousMotion">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_Disabled">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_Discrete">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_Homing">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_StandStill">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_Stopping">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisControl.M_SynchrinizedMotion">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>