<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DiscreteEvents" Id="{a9950c77-75c4-4565-9d6a-64f0c0ce1cfe}" SpecialFunc="None">
    <Declaration><![CDATA[(*
Standard way to set up events to be tied to other parts of the project. might make an interface
*)

FUNCTION_BLOCK FB_DiscreteEvents
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{71612a4f-f6aa-4e09-89dc-467927c53386}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	eventName : STRING;
	evemtID : DINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Execute" Id="{1fd5e78f-7de2-40f0-8ed2-a85a6dac936a}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT M_Execute : HRESULT
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="P_EventId" Id="{cf51e756-b2bf-4a32-9949-f15b5e95182a}">
      <Declaration><![CDATA[PROPERTY PUBLIC P_EventId : Dint]]></Declaration>
      <Get Name="Get" Id="{f62c00b6-2218-4e2c-870d-5cacf6328e6d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{6ff57742-0e5d-4401-a5e2-bf854e8a9974}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="P_EventName" Id="{c298ca1a-b765-48f4-a6ad-9e9372811d6e}">
      <Declaration><![CDATA[PROPERTY PUBLIC P_EventName : String]]></Declaration>
      <Get Name="Get" Id="{21c550db-b1f3-4dcb-aefa-7bb3ab289d89}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_DiscreteEvents">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_DiscreteEvents.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_DiscreteEvents.M_Execute">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_DiscreteEvents.P_EventId.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DiscreteEvents.P_EventId.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DiscreteEvents.P_EventName.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>