<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_PackMLControl" Id="{61f7caa2-4ae2-4c52-ad20-bbdcfbe3e126}" SpecialFunc="None">
    <Declaration><![CDATA[(*
Standard way to control assests in system
*)
FUNCTION_BLOCK ABSTRACT FB_PackMLControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PackMLControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>